# Generated by Django 5.2.4 on 2025-07-09 22:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='data',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
