# Generated by Django 5.2.4 on 2025-07-16 17:29

from django.db import migrations, models
import django.db.models.deletion
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_agendamento_data"),
    ]

    operations = [
        # Add the new fields with temporary nullable/default values
        migrations.AddField(
            model_name='horario',
            name='disciplina',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='core.disciplina'),
        ),
        migrations.AddField(
            model_name='horario',
            name='local',
            field=models.CharField(default='A definir', max_length=100),
        ),
        migrations.AddField(
            model_name='horario',
            name='data_criacao',
            field=models.DateTimeField(default=timezone.now),
        ),
        migrations.AddField(
            model_name='horario',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        # Remove defaults and make disciplina required
        migrations.AlterField(
            model_name='horario',
            name='disciplina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='core.disciplina'),
        ),
        migrations.AlterField(
            model_name='horario',
            name='local',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='horario',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
