# Generated by Django 5.2.4 on 2025-07-16 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_add_horario_required_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="disciplina",
            name="ativo",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="disciplina",
            name="codigo",
            field=models.CharField(default="TEMP0000", max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name="disciplina",
            name="semestre",
            field=models.IntegerField(default=1),
        ),
    ]
