# Generated by Django 5.2.4 on 2025-07-16 17:51

from django.db import migrations
import re


def update_disciplina_codes(apps, schema_editor):
    """
    Update existing Disciplina records with proper codes based on their names.
    """
    Disciplina = apps.get_model('core', 'Disciplina')
    
    for idx, disciplina in enumerate(Disciplina.objects.all()):
        # Generate a code based on the first letters of each word in the name
        words = disciplina.nome.split()
        if words:
            # Get first letters and make uppercase
            letters = ''.join([word[0].upper() for word in words if word])
            # Ensure we have at least 3 letters, pad with 'X' if needed
            letters = (letters + 'XXX')[:3]
            # Add a numeric suffix based on index
            codigo = f"{letters}{idx+1:04d}"
            
            # Clean up any non-alphanumeric characters
            codigo = re.sub(r'[^A-Z0-9]', 'X', codigo)
            
            # Ensure uniqueness by checking if code already exists
            base_codigo = codigo
            counter = 1
            while Disciplina.objects.filter(codigo=codigo).exclude(id=disciplina.id).exists():
                codigo = f"{base_codigo[:-2]}{counter:02d}"
                counter += 1
            
            disciplina.codigo = codigo
            disciplina.save()


def reverse_migration(apps, schema_editor):
    """
    Revert all codes back to default
    """
    Disciplina = apps.get_model('core', 'Disciplina')
    Disciplina.objects.all().update(codigo='TEMP0000')


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_add_disciplina_fields"),
    ]

    operations = [
        migrations.RunPython(update_disciplina_codes, reverse_migration),
    ]
