# Generated by Django 5.2.4 on 2025-07-16 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_update_disciplina_codes"),
    ]

    operations = [
        migrations.AddField(
            model_name="agendamento",
            name="data_atualizacao",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="agendamento",
            name="data_criacao",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="agendamento",
            name="observacoes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="agendamento",
            name="status",
            field=models.CharField(
                choices=[
                    ("agendado", "Agendado"),
                    ("confirmado", "Confirmado"),
                    ("cancelado", "Cancelado"),
                    ("realizado", "Realizado"),
                ],
                default="agendado",
                max_length=20,
            ),
        ),
    ]
