# Generated by Django 5.2.4 on 2025-07-17 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("core", "0007_add_database_indexes"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="agendamento",
            name="aluno",
        ),
        migrations.RemoveField(
            model_name="agendamento",
            name="horario",
        ),
        migrations.AlterModelOptions(
            name="customuser",
            options={},
        ),
        migrations.RenameIndex(
            model_name="disciplina",
            new_name="core_discip_nome_8e6559_idx",
            old_name="disciplina_nome_idx",
        ),
        migrations.RenameIndex(
            model_name="disciplina",
            new_name="core_discip_curso_5d5d00_idx",
            old_name="disciplina_curso_idx",
        ),
        migrations.RenameIndex(
            model_name="disciplina",
            new_name="core_discip_semestr_838bb0_idx",
            old_name="disciplina_semestre_idx",
        ),
        migrations.RenameIndex(
            model_name="disciplina",
            new_name="core_discip_ativo_0981f0_idx",
            old_name="disciplina_ativo_idx",
        ),
        migrations.RenameIndex(
            model_name="horario",
            new_name="core_horari_dia_sem_e1de28_idx",
            old_name="horario_dia_semana_idx",
        ),
        migrations.RenameIndex(
            model_name="horario",
            new_name="core_horari_hora_in_2bbc4a_idx",
            old_name="horario_hora_inicio_idx",
        ),
        migrations.RenameIndex(
            model_name="horario",
            new_name="core_horari_hora_fi_b2b199_idx",
            old_name="horario_hora_fim_idx",
        ),
        migrations.RenameIndex(
            model_name="horario",
            new_name="core_horari_local_3a5060_idx",
            old_name="horario_local_idx",
        ),
        migrations.RenameIndex(
            model_name="horario",
            new_name="core_horari_ativo_a0b6c9_idx",
            old_name="horario_ativo_idx",
        ),
        migrations.RenameIndex(
            model_name="horario",
            new_name="core_horari_ultima__0f80fc_idx",
            old_name="horario_ultima_atualizacao_idx",
        ),
        migrations.AddConstraint(
            model_name="customuser",
            constraint=models.CheckConstraint(
                condition=models.Q(("tipo__in", ["aluno", "professor", "monitor"])),
                name="tipo_usuario_valido",
            ),
        ),
        migrations.DeleteModel(
            name="Agendamento",
        ),
    ]
