# Generated by Django 5.2.4 on 2025-07-18 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_agendamento_aluno_remove_agendamento_horario_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
